/* Study engine v3: persistent full-cycle queue, resume, and appearance counts. */
(function(root){'use strict';
const VERSION=3, STORAGE_KEY='sw_study_engine_v2';
const SUBJECT_ORDER=['社會工作研究方法','人類行為與社會環境','社會工作','社會工作直接服務','社會政策與社會立法'];
function shuffle(items,random){const out=items.slice(),rng=typeof random==='function'?random:Math.random;for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function uniqueQuestions(items){const seen=new Set();return (items||[]).filter(q=>{if(!q||q.id==null||seen.has(String(q.id)))return false;seen.add(String(q.id));return true;});}
function interleaveBySubject(items,random){const buckets=new Map();SUBJECT_ORDER.forEach(s=>buckets.set(s,[]));(items||[]).forEach(q=>{const s=q.subject||'其他';if(!buckets.has(s))buckets.set(s,[]);buckets.get(s).push(q);});buckets.forEach((a,s)=>buckets.set(s,shuffle(a,random)));const out=[];while(Array.from(buckets.values()).some(a=>a.length))for(const a of buckets.values())if(a.length)out.push(a.pop());return out;}
function createState(){return {version:VERSION,pools:{},appearances:{},active:null,updatedAt:null};}
function readState(storage){try{const raw=(storage||root.localStorage).getItem(STORAGE_KEY);if(!raw)return createState();const x=JSON.parse(raw);if(!x||!x.pools)return createState();x.appearances=x.appearances&&typeof x.appearances==='object'?x.appearances:{};x.version=VERSION;return x;}catch(_){return createState();}}
function writeState(state,storage){state.version=VERSION;state.appearances=state.appearances&&typeof state.appearances==='object'?state.appearances:{};state.updatedAt=new Date().toISOString();try{(storage||root.localStorage).setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch(_){return false;}}
function poolKey(f){f=f||{};return JSON.stringify({year:f.year||'all',subject:f.subject||'all'});}
function beginCycle(items,filters,state,random){const clean=uniqueQuestions(items),key=poolKey(filters),prior=state.pools[key]||{};const queue=interleaveBySubject(clean,random).map(q=>String(q.id));if(queue.length>1&&queue[0]===prior.lastId){const j=queue.findIndex(id=>id!==prior.lastId);if(j>0)[queue[0],queue[j]]=[queue[j],queue[0]];}const pool={cycle:(prior.cycle||0)+1,eligibleCount:clean.length,queue,position:0,currentId:null,seenIds:[],lastId:prior.lastId||null,startedAt:new Date().toISOString()};state.pools[key]=pool;state.active=key;return pool;}
function nextQuestion(items,filters,state,random){const clean=uniqueQuestions(items),key=poolKey(filters);state.appearances=state.appearances&&typeof state.appearances==='object'?state.appearances:{};let pool=state.pools[key];if(!pool||!Array.isArray(pool.queue)||pool.queue.length!==clean.length||pool.position>=pool.queue.length)pool=beginCycle(clean,filters,state,random);if(pool.currentId!=null){pool.lastId=pool.currentId;if(!pool.seenIds.includes(pool.currentId))pool.seenIds.push(pool.currentId);pool.position++;pool.currentId=null;}if(pool.position>=pool.queue.length)pool=beginCycle(clean,filters,state,random);pool.currentId=pool.queue[pool.position];const id=String(pool.currentId);state.appearances[id]=(Number(state.appearances[id])||0)+1;const byId=new Map(clean.map(q=>[String(q.id),q]));return {question:byId.get(id)||null,pool,state};}
function resume(items,filters,state){const pool=state.pools[poolKey(filters)];if(!pool||!Array.isArray(pool.queue))return null;const id=pool.currentId!=null?pool.currentId:pool.queue[pool.position];if(id==null)return null;return uniqueQuestions(items).find(q=>String(q.id)===String(id))||null;}
function appearanceCount(questionId,state){return Number(state&&state.appearances&&state.appearances[String(questionId)])||0;}
function snapshot(state){return JSON.parse(JSON.stringify(state));}
root.SWStudyEngine={version:VERSION,subjectOrder:SUBJECT_ORDER.slice(),shuffle,interleaveBySubject,uniqueQuestions,createState,readState,writeState,poolKey,beginCycle,nextQuestion,resume,appearanceCount,snapshot};
})(window);
/* Per-question tracking and subject accuracy panel; integrated without changing the quiz flow. */
(function(){'use strict';
const KEY='sw_quiz_stats_v1';let installed=false;
function mount(){if(installed||!document.body)return;installed=true;const section=document.createElement('section');section.className='panel';section.id='questionAnalytics';section.innerHTML='<h2>逐題作答與弱科分析</h2><p class="muted">依每題歷次作答統計；答錯率較高的科目會列在前面。資料會跟隨網站原有雲端同步。</p><div id="subjectAnalytics"></div><div id="questionAnalyticsList"></div>';
const history=document.getElementById('examHistory')?.parentElement;if(history)history.after(section);else document.querySelector('main')?.append(section);render();}
function render(){const raw=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}})();const by=raw.questionHistory&&typeof raw.questionHistory==='object'?raw.questionHistory:{};const subjects={};Object.values(by).forEach(q=>{const s=q.subject||'未分類';if(!subjects[s])subjects[s]={attempts:0,wrong:0,correct:0};subjects[s].attempts+=q.attempts||0;subjects[s].wrong+=q.wrong||0;subjects[s].correct+=q.correct||0;});const sh=document.getElementById('subjectAnalytics'),qh=document.getElementById('questionAnalyticsList');if(!sh||!qh)return;sh.replaceChildren();const ranked=Object.entries(subjects).sort((a,b)=>(b[1].wrong/Math.max(1,b[1].attempts))-(a[1].wrong/Math.max(1,a[1].attempts)));if(!ranked.length)sh.textContent='尚無逐題紀錄，完成作答後會顯示。';ranked.forEach(([name,v])=>{const p=document.createElement('p');p.className='status';p.textContent=`${name}｜作答 ${v.attempts} 次｜答對 ${v.correct}、答錯 ${v.wrong}｜答錯率 ${Math.round(v.wrong/Math.max(1,v.attempts)*100)}%`;sh.append(p)});qh.replaceChildren();const rows=Object.values(by).sort((a,b)=>(b.wrong/Math.max(1,b.attempts))-(a.wrong/Math.max(1,a.attempts))).slice(0,100);if(!rows.length)return;const table=document.createElement('div');rows.forEach(q=>{const p=document.createElement('p');p.className='status';p.textContent=`${q.subject||'未分類'}｜${q.year||''}年｜題號 ${q.id}｜作答 ${q.attempts} 次、答對 ${q.correct}、答錯 ${q.wrong}｜最近：${q.lastResult||'—'}`;table.append(p)});qh.append(table);}
function record(q,correct){const raw=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}})();raw.questionHistory=raw.questionHistory&&typeof raw.questionHistory==='object'?raw.questionHistory:{};const id=String(q.id),r=raw.questionHistory[id]||{id,subject:q.subject||'未分類',year:q.year||'',attempts:0,correct:0,wrong:0};r.subject=q.subject||r.subject;r.year=q.year||r.year;r.attempts++;if(correct)r.correct++;else r.wrong++;r.lastResult=correct?'答對':'答錯';r.lastAt=new Date().toISOString();raw.questionHistory[id]=r;localStorage.setItem(KEY,JSON.stringify(raw));}
function observeSave(value){let s;try{s=JSON.parse(value)}catch(_){return}if(!s||typeof s!=='object')return;const quiz=document.getElementById('quiz'),feedback=document.getElementById('feedback');if(quiz&&!quiz.hidden&&feedback&&!feedback.hidden&&document.getElementById('subjectTag')?.textContent){const question=document.getElementById('question')?.textContent||'';const selected=[...document.querySelectorAll('#choices .choice')].find(b=>b.classList.contains('selected'));const correct=feedback.textContent.startsWith('答對');const key=Object.keys(s.questionHistory||{});const idGuess=window.__swLastTrackedQuestion;if(idGuess!==question){const q={id:question,subject:document.getElementById('subjectTag').textContent,year:document.getElementById('year')?.value||''};record(q,correct);window.__swLastTrackedQuestion=question;}}
const review=document.getElementById('mockReview');if(review&&review.children.length&&document.getElementById('mockResults')&&!document.getElementById('mockResults').hidden){[...review.children].forEach((article,i)=>{const h=article.querySelector('strong')?.textContent||'';const qtext=article.querySelector('p')?.textContent||'';const token='mock:'+((document.getElementById('year')?.value)||'')+':'+i+':'+qtext;if(window.__swMockTracked?.includes(token))return;const subject=(h.split('｜')[1]||'未分類').trim();const correct=h.includes('｜答對｜');record({id:token,subject,year:document.getElementById('year')?.value||''},correct);window.__swMockTracked=window.__swMockTracked||[];window.__swMockTracked.push(token);});}render();}
const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const result=original.call(this,k,v);if(k===KEY){try{observeSave(v)}catch(e){console.warn('逐題紀錄未能更新',e)}}return result;};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();