/* Study engine v3: persistent full-cycle queue, resume, and appearance counts. */
(function(root){'use strict';
const VERSION=3, STORAGE_KEY='sw_study_engine_v2';
const SUBJECT_ORDER=['社會工作研究方法','人類行為與社會環境','社會工作','社會工作直接服務','社會政策與社會立法'];
function shuffle(items,random){const out=items.slice(),rng=typeof random==='function'?random:Math.random;for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function uniqueQuestions(items){const seen=new Set();return (items||[]).filter(q=>{if(!q||q.id==null||seen.has(String(q.id)))return false;seen.add(String(q.id));return true;});}
function interleaveBySubject(items,random){const buckets=new Map();SUBJECT_ORDER.forEach(s=>buckets.set(s,[]));(items||[]).forEach(q=>{const s=q.subject||'其他';if(!buckets.has(s))buckets.set(s,[]);buckets.get(s).push(q);});buckets.forEach((a,s)=>buckets.set(s,shuffle(a,random)));const out=[];while(Array.from(buckets.values()).some(a=>a.length))for(const a of buckets.values())if(a.length)out.push(a.pop());return out;}
function createState(){return {version:VERSION,pools:{},appearances:{},active:null,updatedAt:null};}
function readState(storage){try{const raw=(storage||root.localStorage).getItem(STORAGE_KEY);if(!raw)return createState();const x=JSON.parse(raw);if(!x||!x.pools)return createState();x.appearances=x.appearances&&typeof x.appearances==='object'?x.appearances:{};x.version=VERSION;return x;}catch(_){return createState();}}
function writeState(state,storage){state.version=VERSION;state.appearances=state.appearances&&typeof state.appearances==='object'?state.appearances:{};state.updatedAt=new Date().toISOString();try{(storage||root.localStorage).setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch(_){return false;}}
function poolKey(f){f=f||{};return JSON.stringify({year:f.year||'all',subject:f.subject||'all'});}
function beginCycle(items,filters,state,random){const clean=uniqueQuestions(items),key=poolKey(filters),prior=state.pools[key]||{};const queue=interleaveBySubject(clean,random).map(q=>String(q.id));if(queue.length>1&&queue[0]===prior.lastId){const j=queue.findIndex(id=>id!==prior.lastId);if(j>0)[queue[0],queue[j]]=[queue[j],queue[0]];}const pool={cycle:(prior.cycle||0)+1,eligibleCount:clean.length,queue,position:0,currentId:null,seenIds:[],lastId:prior.lastId||null,startedAt:new Date().toISOString()};state.pools[key]=pool;state.active=key;return pool;}
function nextQuestion(items,filters,state,random){const clean=uniqueQuestions(items),key=poolKey(filters);state.appearances=state.appearances&&typeof state.appearances==='object'?state.appearances:{};let pool=state.pools[key];if(!pool||!Array.isArray(pool.queue)||pool.queue.length!==clean.length||pool.position>=pool.queue.length)pool=beginCycle(clean,filters,state,random);if(pool.currentId!=null){pool.lastId=pool.currentId;if(!pool.seenIds.includes(pool.currentId))pool.seenIds.push(pool.currentId);pool.position++;pool.currentId=null;}if(pool.position>=pool.queue.length)pool=beginCycle(clean,filters,state,random);pool.currentId=pool.queue[pool.position];const id=String(pool.currentId);state.appearances[id]=(Number(state.appearances[id])||0)+1;const byId=new Map(clean.map(q=>[String(q.id),q]));return {question:byId.get(id)||null,pool,state};}
function resume(items,filters,state){const pool=state.pools[poolKey(filters)];if(!pool||!Array.isArray(pool.queue))return null;const id=pool.currentId!=null?pool.currentId:pool.queue[pool.position];if(id==null)return null;return uniqueQuestions(items).find(q=>String(q.id)===String(id))||null;}
function appearanceCount(questionId,state){return Number(state&&state.appearances&&state.appearances[String(questionId)])||0;}
function snapshot(state){return JSON.parse(JSON.stringify(state));}
root.SWStudyEngine={version:VERSION,subjectOrder:SUBJECT_ORDER.slice(),shuffle,interleaveBySubject,uniqueQuestions,createState,readState,writeState,poolKey,beginCycle,nextQuestion,resume,appearanceCount,snapshot};
})(window);
