/* Study engine v3: persistent full-cycle queue, resume, and appearance counts. */
(function(root){'use strict';
const VERSION=3, STORAGE_KEY='sw_study_engine_v2';
const SUBJECT_ORDER=['社會工作研究方法','人類行為與社會環境','社會工作','社會工作直接服務','社會政策與社會立法'];
function shuffle(items,random){const out=items.slice(),rng=typeof random==='function'?random:Math.random;for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function uniqueQuestions(items){const seen=new Set();return (items||[]).filter(q=>{if(!q||q.id==null||seen.has(String(q.id)))return false;seen.add(String(q.id));return true;});}
function interleaveBySubject(items,random){const buckets=new Map();SUBJECT_ORDER.forEach(s=>buckets.set(s,[]));(items||[]).forEach(q=>{const s=q.subject||'其他';if(!buckets.has(s))buckets.set(s,[]);buckets.get(s).push(q);});buckets.forEach((a,s)=>buckets.set(s,shuffle(a,random)));const out=[];while(Array.from(buckets.values()).some(a=>a.length))for(const a of buckets.values())if(a.length)out.push(a.pop());return out;}
function createState(){return {version:VERSION,pools:{},appearances:{},active:null,updatedAt:null};}
function readState(storage){try{const raw=(storage||root.localStorage).getItem(STORAGE_KEY);if(!raw)return createState();const x=JSON.parse(raw);if(!x||!x.pools)return createState();x.appearances=x.appearances&&typeof x.appearances==='object'?x.appearances:{};x.version=VERSION;return x;}catch(_){return createState();}}
function writeState(state,storage){state.version=VERSION;state.appearances=state.appearances&&typeof state.appearances==='object'?state.appearances:{};state.updatedAt=new Date().toISOString();try{(storage||root.localStorage).setItem(STORAGE_KEY,JSON.stringify(state));return true;}catch(_){return false;}}
function poolKey(f){f=f||{};return JSON.stringify({year:f.year||'all',subject:f.subject||'all'});}
function beginCycle(items,filters,state,random){const clean=uniqueQuestions(items),key=poolKey(filters),prior=state.pools[key]||{};const queue=interleaveBySubject(clean,random).map(q=>String(q.id));if(queue.length>1&&queue[0]===prior.lastId){const j=queue.findIndex(id=>id!==prior.lastId);if(j>0)[queue[0],queue[j]]=[queue[j],queue[0]];}const pool={cycle:(prior.cycle||0)+1,eligibleCount:clean.length,queue,position:0,currentId:null,seenIds:[],lastId:prior.lastId||null,startedAt:new Date().toISOString()};state.pools[key]=pool;state.active=key;return pool;}
function nextQuestion(items,filters,state,random){const clean=uniqueQuestions(items),key=poolKey(filters);state.appearances=state.appearances&&typeof state.appearances==='object'?state.appearances:{};let pool=state.pools[key];if(!pool||!Array.isArray(pool.queue)||pool.queue.length!==clean.length||pool.position>=pool.queue.length)pool=beginCycle(clean,filters,state,random);if(pool.currentId!=null){pool.lastId=pool.currentId;if(!pool.seenIds.includes(pool.currentId))pool.seenIds.push(pool.currentId);pool.position++;pool.currentId=null;}if(pool.position>=pool.queue.length)pool=beginCycle(clean,filters,state,random);pool.currentId=pool.queue[pool.position];const id=String(pool.currentId);state.appearances[id]=(Number(state.appearances[id])||0)+1;const byId=new Map(clean.map(q=>[String(q.id),q]));return {question:byId.get(id)||null,pool,state};}
function resume(items,filters,state){const pool=state.pools[poolKey(filters)];if(!pool||!Array.isArray(pool.queue))return null;const id=pool.currentId!=null?pool.currentId:pool.queue[pool.position];if(id==null)return null;return uniqueQuestions(items).find(q=>String(q.id)===String(id))||null;}
function appearanceCount(questionId,state){return Number(state&&state.appearances&&state.appearances[String(questionId)])||0;}
function snapshot(state){return JSON.parse(JSON.stringify(state));}
root.SWStudyEngine={version:VERSION,subjectOrder:SUBJECT_ORDER.slice(),shuffle,interleaveBySubject,uniqueQuestions,createState,readState,writeState,poolKey,beginCycle,nextQuestion,resume,appearanceCount,snapshot};
})(window);
/* Question analytics: quick answers and completed mock exams. */
(function(){'use strict';const KEY='sw_quiz_stats_v1';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(_){return {}}}
function render(){const host=document.getElementById('examHistory');if(!host||document.getElementById('questionAnalytics'))return;const section=document.createElement('section');section.className='panel';section.id='questionAnalytics';section.innerHTML='<h2>逐題作答與弱科分析</h2><p class="muted">快問快答及已交卷模擬考的逐題紀錄；答錯率以已作答題數計算，未答另行統計。</p><div id="subjectAnalytics"></div><div id="questionAnalyticsList"></div>';host.parentElement.after(section);}
function refresh(){render();const root=document.getElementById('questionAnalytics');if(!root)return;const raw=read(),items=Object.values(raw.questionHistory||{}),groups={};items.forEach(q=>{const s=q.subject||'未分類';groups[s]??={n:0,w:0,c:0,u:0};groups[s].n+=Number(q.attempts)||0;groups[s].w+=Number(q.wrong)||0;groups[s].c+=Number(q.correct)||0;groups[s].u+=Number(q.unanswered)||0});const sh=root.querySelector('#subjectAnalytics'),qh=root.querySelector('#questionAnalyticsList');sh.replaceChildren();const ranked=Object.entries(groups).sort((a,b)=>b[1].w/Math.max(1,b[1].w+b[1].c)-a[1].w/Math.max(1,a[1].w+a[1].c));if(!ranked.length)sh.textContent='尚無逐題紀錄。';ranked.forEach(([s,v])=>{const p=document.createElement('p');p.className='status';p.textContent=`${s}｜出現 ${v.n} 次｜答對 ${v.c}、答錯 ${v.w}、未答 ${v.u}｜已作答答錯率 ${Math.round(v.w/Math.max(1,v.w+v.c)*100)}%`;sh.append(p)});qh.replaceChildren();items.sort((a,b)=>(Number(b.wrong)||0)/Math.max(1,(Number(b.wrong)||0)+(Number(b.correct)||0))-(Number(a.wrong)||0)/Math.max(1,(Number(a.wrong)||0)+(Number(a.correct)||0))).slice(0,100).forEach(q=>{const p=document.createElement('p');p.className='status';p.textContent=`${q.subject}｜${q.year}｜${q.question||q.id}｜出現 ${q.attempts} 次、答對 ${q.correct}、答錯 ${q.wrong}、未答 ${q.unanswered||0}`;qh.append(p)});}
function saveResult({id,subject,year,question,result,mode}){if(!question)return;const raw=read();raw.questionHistory=raw.questionHistory&&typeof raw.questionHistory==='object'?raw.questionHistory:{};const key=`${mode}:${year}|${subject}|${id}`;const r=raw.questionHistory[key]||{id:key,subject,year,question,attempts:0,correct:0,wrong:0,unanswered:0};r.attempts=Number(r.attempts)||0;r.correct=Number(r.correct)||0;r.wrong=Number(r.wrong)||0;r.unanswered=Number(r.unanswered)||0;r.attempts++;if(result==='答對')r.correct++;else if(result==='未答')r.unanswered++;else if(result==='答錯')r.wrong++;r.lastResult=result;r.lastAttemptAt=new Date().toISOString();raw.questionHistory[key]=r;try{localStorage.setItem(KEY,JSON.stringify(raw))}catch(_){} }
function recordQuick(){const feedback=document.getElementById('feedback'),quiz=document.getElementById('quiz');if(!quiz||quiz.hidden||!feedback||feedback.hidden)return;const question=(document.getElementById('question')?.textContent||'').trim(),subject=(document.getElementById('subjectTag')?.textContent||'未分類').trim(),year=document.getElementById('year')?.value||'',text=feedback.textContent.trim();if(!question||!text)return;const result=text.startsWith('答對')?'答對':text.startsWith('答錯')?'答錯':'';if(result)saveResult({id:question,subject,year,question,result,mode:'quick'});refresh();}
function recordMock(){const results=document.getElementById('mockResults'),review=document.getElementById('mockReview');if(!results||results.hidden||!review)return;review.querySelectorAll('article').forEach(article=>{const heading=article.querySelector('strong')?.textContent||'',body=article.querySelector('p')?.textContent||'';const subject=(heading.split('｜')[1]||'未分類').trim(),year=document.getElementById('year')?.value||'',question=body.split('\n')[0].trim();if(!question)return;const result=heading.includes('未答')?'未答':heading.includes('答錯')?'答錯':heading.includes('答對')?'答對':'';if(result)saveResult({id:question,subject,year,question,result,mode:'mock'});});refresh();}
document.addEventListener('click',e=>{if(e.target.closest('#choices .choice'))queueMicrotask(recordQuick);if(e.target.closest('#submitMock'))queueMicrotask(recordMock)});document.addEventListener('DOMContentLoaded',refresh,{once:true});if(document.readyState!=='loading')refresh();
})();